apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocdnodejsapp.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "argocdnodejsapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "argocdnodejsapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argocdnodejsapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "argocdnodejsapp.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
